CREATE TABLE mytable(
   columbary_ID           VARCHAR(30) NOT NULL PRIMARY KEY
  ,cr_vault_number        VARCHAR(11) NOT NULL
  ,cr_full_name           VARCHAR(21) NOT NULL
  ,cr_permanent_residence VARCHAR(60) NOT NULL
  ,cr_mobile_number       VARCHAR(22) NOT NULL
  ,cr_email_address       VARCHAR(35) NOT NULL
  ,cr_date_of_issuance    DATE  NOT NULL
  ,cr_date_of_expiration  DATE  NOT NULL
  ,cr_issuing_party       VARCHAR(30) NOT NULL
  ,first_beneficiary      VARCHAR(20) NOT NULL
  ,second_beneficiary     VARCHAR(18) NOT NULL
  ,third_beneficiary      VARCHAR(21) NOT NULL
  ,fourth_beneficiary     VARCHAR(20) NOT NULL
  ,pa_type_of_p           VARCHAR(19) NOT NULL
  ,pa_amount              INTEGER  NOT NULL
  ,pa_ref_number          INTEGER  NOT NULL
);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'51-B-South','Bradley Rivera','21385 Thomas Stream, Kimberlyfort, LA 46870','676.006.9112','sampsonarthur@moore-dean.org','30/08/2024','23/08/2027','Brown-Mckenzie','Roberto May','William Ortega','Andrea Love','Robert Ward','PartialContribution',158324,964740);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'75-A-North','Austin Nelson','9395 Samantha Bridge Suite 349, New Kyleburgh, NE 34652','911-622-6250x97976','wbrown@tate.info','25/10/2022','24/08/2026','Reed-Hill','Mike Combs','Holly Davis','Angela Oconnor','Michelle Young','PartialContribution',183552,912043);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'31-D-North','Roy Mercer','68171 Hurley Parks Apt. 108, Wilsonville, ME 25871','+1-245-775-6538x700','robert48@yahoo.com','15/04/2024','4/11/2029','Buchanan-Richards','Hannah Anderson','Luke Horton','Courtney Brooks','Bradley Fleming','FullContribution',233900,987377);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'12-B-North','Brian Young','83560 Rhodes Hills Suite 971, Lake Anthony, VT 86054','893-443-5702x548','matthew06@yahoo.com','2/3/2020','14/06/2026','Mercado, Rivera and Fitzgerald','Anthony Kennedy','William Hughes','Martin Rhodes','Alejandro Perez','PartialContribution',269977,931666);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'63-B-South','Nicholas Rodriguez','1718 Brooks Groves, Laurenhaven, AK 87202','489.779.7817x01202','jeffreybowman@yahoo.com','16/04/2023','5/4/2026','Hunt LLC','Brenda Edwards','Jay Newman','Brandon Lucas','Catherine Castro','PartialContribution',228093,917258);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'47-A-South','Katie Gutierrez','62895 David Courts Suite 211, Feliciatown, AL 38578','5261986553','kevin65@gmail.com','28/05/2022','16/03/2026','Phillips Ltd','Lynn Parker','Lisa Gonzales','Lauren Weiss','Rebecca Smith','PartialContribution',128687,919104);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'22-C-North','Kyle Acosta','5800 Lee Fork, Thomaston, ME 34235','954-915-2731x78852','coxkari@gmail.com','4/1/2024','27/12/2029','Williams-Schmidt','Crystal Holt','Debra Evans','Rachael Day','Stephen Taylor','FullContribution',85892,922387);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'20-B-North','Terry Edwards','1024 Hansen Route, North Ralphburgh, PA 56368','-3807','xerickson@fernandez-buchanan.net','24/10/2021','6/6/2027','Haley, Hinton and Lamb','Renee Jimenez','Jennifer Martin','Scott Johnson','David Walker','PartialContribution',133465,973512);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'45-C-South','Michael Dixon','4058 Todd Harbors Suite 482, Port Meghanhaven, UT 56808','552-163-0811x785','brandon57@gmail.com','31/03/2020','6/1/2026','Scott, Simon and Johnson','Eric Williams','Charles Moses','Edward Hoover','Vanessa Fischer','FullContribution',86636,994844);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'63-A-South','Zachary Olsen','9921 Kyle Tunnel Suite 042, Pricechester, TX 21381','-7165','gregory14@deleon.com','29/11/2020','7/9/2027','Curry PLC','Helen Lewis','Chad Johnson','Denise Smith','Michelle Green','FullContribution',276848,989114);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'62-D-South','David Gonzalez','5579 Williams Summit Apt. 591, Toddtown, MI 19410','001-818-199-7975x39721','xcosta@yahoo.com','16/09/2022','11/1/2026','Hines, Parsons and Davis','Alexa Mcdowell','Joseph Watson','Shawn Ellison','Mr. Benjamin Floyd','FullContribution',179405,954736);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'67-B-South','Alex Davis','926 Swanson Greens Apt. 858, Pricechester, MT 99816','-5979','warrenmary@hotmail.com','23/03/2020','7/8/2029','Cox Inc','Danielle Manning','Jennifer White','Rebecca Ward','Karen Johnson','FullContribution',222340,938694);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'82-A-South','Krista Farmer','31137 Williams Common Suite 003, New Vincent, AL 26794','017-123-9998x642','david87@yahoo.com','11/1/2024','27/08/2026','Burns Inc','Gregory Quinn','Jeremiah Smith','Frank Macias','Hector Willis','FullContribution',228323,938679);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'42-D-North','Joel Roberts','624 Charles Greens Suite 549, Parkbury, MD 62614','001-491-621-6856x6013','uchapman@jones.org','25/12/2024','22/10/2026','Mills, Rodriguez and White','Tyler Lopez','James House','David Gutierrez','Ashley Shaw','FullContribution',78029,974766);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'38-C-North','Justin Murphy','39640 Joseph Orchard, South Donna, AR 48956','(778)168-4104x24212','xnielsen@reed.com','23/06/2020','1/4/2026','Craig, Holden and Arnold','Kristina Thornton','Kenneth Robinson','Ian Parsons','Sandra Mayer','PartialContribution',211414,989170);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'8-C-South','Shelby Allen','7099 Russell Light, Derrickborough, MO 78167','454.124.0260x1928','james05@clark-wade.com','1/4/2024','7/4/2026','Gonzalez-Booth','Mark Larson','Elijah Sherman','Elizabeth Haney','Alejandra Alvarez','FullContribution',166702,963470);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'19-D-North','Michael Chang','USCGC Stark, FPO AA 95410','-8645','leslieburns@yahoo.com','16/02/2020','13/07/2029','Schmidt-Fowler','Mr. Michael Schultz','Joshua Montgomery','Michael Williams','James Cruz','PartialContribution',257032,923457);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'94-C-North','Justin Fleming','03263 Thomas Green Suite 901, West Charles, NV 14538','+1-349-506-6006x8928','randallwilliams@brown-wyatt.info','11/4/2021','8/2/2029','Carpenter-Smith','Robert Richardson','Zachary Cooper','Whitney Garza','Kayla Martinez','PartialContribution',266435,912118);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'100-D-South','Christopher Owens','USCGC Perez, FPO AP 45932','001-755-182-7154x53859','tyler84@wong.com','10/3/2020','23/02/2026','Williams, Simmons and Martinez','Brittany Woods','Joel Price','Joseph Munoz','Jennifer Garner','PartialContribution',198885,974427);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'83-B-South','Larry Welch','74398 Jeffrey Knoll Apt. 855, Lauraville, MT 13835','(487)652-5514','bbrown@hotmail.com','30/04/2024','16/07/2027','English, Baker and Miller','Thomas Diaz','Nicholas Gomez','Derrick Carter','Dr. Alicia Johnson','PartialContribution',90152,926889);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'46-D-North','Kelly Mcdowell','PSC 2404, Box 7745, APO AP 91462','+1-501-357-8469x74733','newmanroy@hotmail.com','10/4/2024','1/11/2028','Jones Group','Sierra Lang MD','Carol Gentry','Mason Reynolds','James Wise','FullContribution',144180,993612);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'99-A-North','Kara Johnson','11187 Dennis Isle Suite 390, Pollardchester, SC 39178','(886)486-4151x0606','courtneyhiggins@brown.com','11/6/2024','8/12/2028','Garrett PLC','James Sullivan','Laura Wolfe','Joseph Ramirez','Steven Cox','FullContribution',121616,938012);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'17-D-North','Christine Taylor','68384 Christopher Cove, Christinaville, MD 41654','001-762-568-6183x66657','nancyroberts@young.info','26/10/2020','13/11/2028','Schwartz-Brooks','Valerie Lowe','Edward Smith','Michelle Nelson','Sean Henderson','FullContribution',70973,998263);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'90-B-South','Melissa Singleton','710 Morrison Field Suite 267, New Jacobville, HI 67522','+1-687-130-0169x7907','dennisjames@jackson-dennis.net','12/6/2022','11/11/2026','Strickland-Smith','Paige Henry','Justin Contreras','Amy Kelly','Laura White','FullContribution',231376,977744);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'70-D-South','Robert Allen','23884 Megan Keys Apt. 891, East Keith, MS 77237','+1-491-354-8320x4423','matthew66@martin.org','8/7/2022','4/1/2029','Pena, Carr and Griffin','Robert Dunlap','Denise Reid','Scott Sanchez','Anita Morrison','PartialContribution',290028,951936);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'9-B-North','Joshua Tucker','3886 Christopher Ridge Suite 348, Arthurmouth, OH 03759','4688543220','charleshuffman@gmail.com','21/06/2023','11/2/2026','Keith Ltd','Ariel Kim','Deborah Patterson','Stephanie Nielsen','David Jordan','FullContribution',270529,963685);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'82-B-South','Jason Webster','733 Stephen Union Apt. 686, South Lauraburgh, VT 22370','+1-437-520-0264x94719','nperez@yahoo.com','30/07/2023','8/1/2028','Fuller-Stevens','Samantha Kennedy','Peter Lyons','Karen Gutierrez','Sharon Mcdaniel','PartialContribution',125061,948971);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'73-D-South','Crystal Vega','2549 Sara Hills, Whitefurt, IN 17769','920-537-8910x125','matthew15@gmail.com','26/07/2020','13/11/2028','Peck, Blackburn and Johnson','Joanna Maldonado','Shane Barber','Elizabeth Lloyd','Sarah Brown','FullContribution',151535,986607);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'10-C-North','James Cobb','591 Hensley Walks, Reidside, AR 30470','-2901','ashleycannon@gmail.com','28/04/2023','25/12/2028','Tate and Sons','David Raymond','Tara Smith','Roberta Webster','Shaun Nelson','PartialContribution',78162,964404);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'2-B-South','Timothy Freeman','44045 Carl Ranch, New Alexanderborough, MT 69817','001-279-823-6505','lopezcalvin@hotmail.com','28/12/2020','13/03/2027','Olsen, Thompson and Chen','Ashley Fritz','Jessica Neal','Debra Leblanc','Tanya Williams','PartialContribution',105743,994269);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'76-B-North','Autumn Pacheco MD','039 Bernard Fields Suite 614, Lopezfurt, IL 17479','907.286.0035x1484','kimjames@hotmail.com','27/04/2024','4/10/2028','Hoover-Holmes','Taylor Clark','Brett Pineda','Dennis Reed','Angela Soto','FullContribution',89549,976889);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'37-D-North','Sandra Thomas','722 Michael Mill, Brownchester, UT 53473','(243)612-9996','ernestedwards@reed.com','31/03/2023','11/1/2028','Cisneros Inc','Heidi Parsons','Kayla Ortiz','Zachary Oconnor','Lori Watts','FullContribution',286365,997044);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'22-C-South','Omar Porter','9556 Lauren Grove, Lake Matthew, IL 15405','568.794.6650x013','youngjessica@gmail.com','24/08/2020','13/10/2026','Brown-Mcgee','Henry Turner','Sandra Simmons','Megan Andrade','Kristina Wilcox','PartialContribution',284549,932486);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'95-D-South','Mrs. Yolanda Williams','520 Jackson Forges Suite 509, Jessicaside, ID 19108','(667)132-7859x04483','rreynolds@guerrero.com','29/11/2023','28/10/2029','Cuevas-Griffin','Stephanie Zimmerman','Joshua Robinson','Travis Carter','Ryan Hoffman','PartialContribution',58137,965702);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'55-B-South','Kimberly Navarro','29977 Tanya Knoll, New Adamchester, LA 32047','+1-152-787-5761x7472','morristaylor@foster.com','10/11/2021','25/03/2029','Rocha Group','Julia Long','Catherine Chase','Angela Stevens','David Beck','PartialContribution',198577,932990);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'10-C-South','Mary Foster','55727 Dawson Crest, Lake Michael, MS 61410','001-150-707-3873x8243','cbowman@gmail.com','7/7/2021','7/9/2028','Pitts-Pollard','Allison Phillips','Mary Bates','Luke Bell','Christina Martinez','PartialContribution',184384,947618);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'92-C-South','Brianna Ford','9470 Garrison Track Suite 099, Katrinaburgh, AZ 17318','496.981.6408x1556','gonzalezsusan@morgan-hill.net','22/07/2024','4/10/2027','Kelley and Sons','Andrew Hoover','John Wood','Kathy Cervantes','Steven Jefferson','PartialContribution',209495,975742);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'3-A-South','Jessica Wade','4519 Patterson Shoals Suite 864, South Chadtown, WI 69444','500-129-0453x17421','zlawrence@yahoo.com','18/07/2023','21/09/2026','Miranda Ltd','Jennifer Garcia','Jason Richards','Derek Green','Brian Cooper','FullContribution',286904,910543);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'15-D-North','Mark Nguyen','4978 Haney Parks Suite 818, Millerville, MN 66017','001-244-471-2384x206','alicia95@lopez.com','17/07/2020','27/05/2028','Wilson LLC','Willie Salazar','John Gray','Christopher Ramirez','Brian Watson','FullContribution',115752,942092);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'94-D-North','Timothy Keith','57074 Ellison Mission, Kennedyborough, WV 93129','309.731.5871x431','kenneth19@gmail.com','12/10/2024','9/11/2029','Hall-Garrett','Felicia Rich','Brian Kirby','Joshua Nelson DDS','Rebecca Ruiz','PartialContribution',70824,941615);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'82-A-South','Michael Stewart','3025 Dana Manors Apt. 667, Leslieberg, PA 45226','+1-706-663-1269x90405','danielledavis@campbell-dixon.com','23/03/2021','9/2/2028','Richards, Scott and Keller','Lindsey Adams','Katelyn Alexander','Jason Molina','Megan Mcdonald','PartialContribution',222860,938752);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'44-A-South','George Le','854 Tracy Views, New Paige, WA 97587','7847458021','chad21@myers-hamilton.biz','10/12/2023','9/6/2029','Hill LLC','John Kelly','Michael Wells','Rachael Cruz','Gloria Kelly','FullContribution',290495,986710);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'90-D-South','Kristen Watson','438 James Passage Suite 753, Port Erinfurt, MA 72757','371-838-9158','uduarte@gmail.com','24/07/2023','3/11/2029','Myers LLC','Nicholas Ward','Sherry Thompson','Sara Turner','Brian Hall PhD','FullContribution',218715,998500);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'22-A-South','Joseph Wiggins','55812 Wilson Mews, Margarethaven, TX 86097','001-015-245-5070x67403','michellefigueroa@wilson.com','9/3/2024','25/04/2028','Stephens, Arnold and Brown','Jose Phillips','Mark Hernandez','Travis Daniels','Christie White','FullContribution',82695,988787);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'77-D-South','Ricky Patterson','82883 Murphy Walk Suite 568, New Michael, MT 14366','5199297388','ywagner@hotmail.com','10/11/2020','8/9/2029','Crawford-Wagner','Rebecca Russell','Kimberly Macias','Kayla Ward','Christina Bryan','FullContribution',279342,941112);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'95-A-North','Donna Kaufman','439 Wallace Canyon, New Jason, SC 23740','165-590-0173x85353','timothycruz@scott.com','16/06/2024','13/08/2027','Marshall-Wong','Ryan Gonzalez','Samantha Vega','Brian Mercado','Johnny Wilson','FullContribution',245497,938116);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'92-C-North','Mark Thompson','51683 Phillips Port Suite 185, West Ethan, CT 98637','734-935-2477','dunnsherry@morales.net','23/05/2024','20/10/2026','Davis, Clayton and Burke','Amy Hughes','Rebecca Malone','Mrs. Heather Fox MD','Mark Fernandez','PartialContribution',243217,991587);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'2-B-North','Jacob Robinson','71789 Connor Burg, East Marvin, KY 23140','-3614','reginald82@hotmail.com','27/03/2022','5/6/2028','Johnson Group','Kevin Gray','Jacob Love','Brian Clark','Travis Green','PartialContribution',281681,976916);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'38-C-North','Debra Case','PSC 4291, Box 7763, APO AP 31001','001-802-375-9827x2331','suzanne18@nelson-davis.info','30/07/2024','20/06/2026','Brady, Bailey and Baker','Anthony Jones','Ricardo Graves','Miranda Reed','William Porter','PartialContribution',198117,984363);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'24-C-North','Rick Garner','2606 Poole Springs, Johnsonburgh, TN 78868','(239)250-2360x25085','toddmiller@munoz.com','5/2/2020','22/10/2028','Carter Ltd','Julie Marks','Matthew Rivers','Jonathan Campbell','Carolyn Marks','FullContribution',280879,921101);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'38-B-South','Steven Sherman','7739 Kelly Locks, East Valerie, OR 81710','001-675-939-2353','ksims@gmail.com','22/11/2023','12/10/2026','Taylor-Watson','Adam Pacheco','Gail Joyce','Maria Wright','Phillip Sullivan','PartialContribution',136342,921615);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'20-D-South','Teresa Browning','72476 Serrano Crest Apt. 792, Scottside, OH 91527','(325)942-6039','ohaynes@hotmail.com','26/09/2021','8/11/2028','Fields-Ross','Sarah Johnson','Lori Dixon','Michael Warren','William Carroll','FullContribution',236041,919264);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'9-D-North','Nicholas Smith','14886 Jenny Junction, Port Thomas, CO 30084','662.451.6481x8188','hernandezmakayla@gmail.com','2/5/2023','2/6/2027','Love Group','Candice Lee','Danny Chavez','Bianca Hamilton','Douglas Perez','FullContribution',213617,911417);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'21-A-North','Jennifer Sanchez','7902 Alvarez Run, South William, VT 82860','(953)378-5579','smoore@griffin-wilson.biz','14/08/2021','12/8/2027','Frank-Jackson','Hayden George','Paul Diaz','Ethan Marshall','Larry Ramirez','FullContribution',275795,944560);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'10-B-North','Marissa Moore','5183 Phillip Isle, Port Madisonshire, MN 25134','(011)004-2146x4554','kball@gmail.com','26/12/2022','4/2/2027','Bradford-Peterson','James Castillo','Shawn Skinner','Dustin Stanley','Alexandra Velasquez','PartialContribution',61735,978339);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'80-A-South','Carrie Beck','8128 Heidi Knolls, North Laurashire, AR 41303','7246273215','wbaker@jacobs-hardy.info','23/03/2020','30/07/2028','Dawson, Howard and Orozco','Sherri Mckinney','Paul Rhodes','James Sanchez','Carolyn Robbins','FullContribution',267237,966900);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'71-A-South','Tracie Wagner','93250 Cline Crescent Apt. 164, New Brandistad, SC 03916','336-777-7008','xbaker@galvan-olsen.org','27/03/2022','15/10/2026','Johnson, Smith and Gardner','Brad Nash DVM','Michelle Williams','Eugene Smith','Jessica Allen','FullContribution',72273,974252);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'46-B-North','John Perry','37266 Chan Knolls Suite 789, West Allison, SD 49575','349-661-9336x22072','arthur01@yahoo.com','29/11/2024','15/12/2027','Greene-Kline','Alan Edwards','Louis Cobb','Timothy King','Andrew Smith','PartialContribution',282347,914880);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'80-A-North','Gina Nelson','405 Cassandra Roads Apt. 307, Mcdonaldside, CO 40066','328.794.1330x62289','samuel06@gmail.com','10/6/2021','31/05/2029','Myers Ltd','Jonathan Morrison','Elizabeth White','Karen Rush','Ryan Suarez','PartialContribution',130121,917093);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'99-D-North','Michael Tapia','448 Johnston Cape, Lake Frankbury, MD 91527','594.866.4559','bwright@christian.com','10/3/2023','23/12/2026','Cobb-Greer','Michael Martin','Michael Oneill','Jose York','Mr. David Smith MD','FullContribution',238840,929086);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'54-A-South','Ariel Velazquez','299 Thomas Forest Apt. 556, West Crystalfurt, NJ 19644','272.515.0392','youngkayla@lewis.com','14/06/2021','13/08/2029','Jones-Mcdonald','Susan Knight','Heather Garcia','Janet Yang','Amanda Washington','PartialContribution',165711,993180);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'92-A-South','Leslie Blevins','3521 Martin Dam Suite 891, Joycefurt, NV 26038','911.472.2033','karawheeler@yahoo.com','9/5/2023','17/06/2028','Spencer Group','Cory Velez','Kyle Smith','Dr. Christine Huffman','Patricia Nolan','FullContribution',69897,950830);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'79-B-North','Clayton Brooks','8521 Jenkins Orchard, New Jacquelinetown, MN 19749','347.431.3137x320','pmartinez@williams-snyder.info','3/6/2023','30/04/2029','Campos Ltd','Dr. Shelby Cross','Jenna Hull','Nicholas Bryan','Jim Carson','FullContribution',74631,945509);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'34-B-North','Gabrielle Ferguson','1251 Rodriguez Corners, Williamfurt, HI 21373','797-101-4408x70919','rhonda27@gmail.com','21/09/2020','1/7/2026','Barajas-Stark','Patrick Lopez','Samuel Powell','Joyce Scott','Charles Hess','FullContribution',153466,967984);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'8-C-North','Tiffany Moore','70782 Kimberly Lodge Apt. 203, Garciahaven, AR 80375','001-798-728-2574x08452','davidmartinez@graves.com','19/06/2020','21/03/2029','Mclean-Baird','Jennifer Martinez','Joshua Johnson','Patricia Montgomery','Michael Nixon','FullContribution',118320,979894);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'60-D-South','Alex Edwards','564 Kenneth Green, South Staceyburgh, DC 89290','(377)001-3674x27876','fosterkatie@gmail.com','26/08/2020','4/1/2029','Myers LLC','Shane Waller','Douglas Nichols','Christopher Mcdonald','Harold Wallace','PartialContribution',234201,971082);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'45-B-North','Brian Wu','42737 Jessica Plains, West Bethmouth, VT 46943','750-467-9665x8481','sullivanbrandi@yahoo.com','24/11/2021','16/09/2027','Wilson-Brown','Melissa Hurley','Helen Flynn','Lonnie Watson','Michael Estrada','PartialContribution',190307,994209);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'82-D-South','Jerry Lam','38091 Dawn Ports, New Brandon, IN 10300','+1-024-384-7777x422','valeriesmith@hotmail.com','26/04/2022','1/12/2029','Williams-Roberts','Carolyn Howard','Mark Williams','Marisa Evans','Lisa Guerrero','FullContribution',286011,936322);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'65-D-South','Sean Russell','40630 Scott Cliff, Brittanymouth, MA 24394','166-586-1132','michelle89@gmail.com','1/6/2021','8/1/2028','Thompson, Leonard and Jones','David Gallegos','James Woodard','Whitney Lee','Rachel Adams','PartialContribution',196832,949435);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'58-B-South','Jessica Hutchinson','215 Parks Meadow Suite 957, South Thomasborough, TN 10456','009.356.4950','nicholas51@yahoo.com','13/03/2021','13/05/2028','Kelly-Chandler','Ryan Lara','Dillon Allen','Autumn Mcdonald','Jacqueline Rodriguez','PartialContribution',133781,980313);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'93-C-North','Ryan Serrano','8111 Holmes Key Apt. 714, East Christy, NH 90246','(843)723-5491','toddjones@hunt-jordan.com','23/01/2023','25/08/2027','Wilkins Group','Kevin Baker','Nicholas Higgins','Sheri Johnson','Nicholas Ballard','FullContribution',61427,953202);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'48-D-South','Michelle Livingston','442 Karen Freeway, Fosterhaven, TX 23058','001-458-756-1312x273','weaverashley@perkins-miller.com','31/05/2020','13/02/2027','Hall, Herrera and Brown','Robert Sullivan','Alejandro Caldwell','Jasmine Galloway','Lucas Ayers','PartialContribution',110208,954423);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'36-B-North','Alicia Gregory','956 Lewis River Apt. 970, South Dianamouth, OR 16371','899-117-7028x7256','johnsonryan@roberts.com','27/03/2021','7/1/2026','Taylor, Stout and Johnson','Emily Mason','Amanda Salazar','Christopher Howard','Robyn Benson','PartialContribution',171614,923412);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'44-A-North','Amanda Vega','7413 Ashley Union, Michaelberg, NV 78645','375.955.4028x376','susanjohnson@maldonado.biz','21/04/2021','24/01/2027','Palmer Ltd','Kendra Goodwin','Todd Miller','Jessica Knight','Jeremiah Wright','FullContribution',75774,950172);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'2-C-South','Tyler Pruitt','4702 Jennifer Canyon Apt. 364, Cohenborough, ME 20228','+1-650-783-3133x518','thomas15@dodson-diaz.com','13/02/2021','7/2/2028','Kirby-Morgan','Tommy Ruiz','Steven Leblanc','Stephanie Hopkins','Jeremy Allen','FullContribution',126553,942219);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'32-C-South','Jonathan Reynolds','7053 Allen Burgs, South Don, CT 74394','605-405-4320x0634','josephgolden@cooper.info','31/07/2020','20/06/2029','Coleman, Terry and Lewis','Alexis Sparks','Steven Turner','Timothy Gonzalez','Joseph Stone','FullContribution',232678,922131);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'50-B-South','Lisa Williamson','269 Sara Shores, Lake Angelabury, ID 46611','001-219-172-1391x970','moorecrystal@hotmail.com','12/2/2020','1/2/2027','Miller-Pollard','Sharon Reynolds MD','Jesus Tanner','Dalton Sanchez','Jonathan Hester','FullContribution',111547,975949);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'14-B-North','Melissa Decker','728 Krystal Harbors, Meyerchester, AZ 81088','045-368-3294x21937','pgraham@gmail.com','16/04/2022','26/11/2028','Leach-Morris','Jessica Jennings','Kurt Lutz','Cassandra Rosales','Haley Smith','PartialContribution',248553,929544);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'79-D-South','Brenda Pearson','663 Joel Burgs, South Natalie, KY 86754','405-610-3728x6881','danieljackson@maldonado.com','7/12/2023','15/12/2027','Ware, Bailey and Armstrong','Judith Palmer','Paul Lee','Katherine Strickland','Christopher Murphy','PartialContribution',296078,989200);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'36-D-South','Jennifer Riley','13231 Banks Ports Apt. 820, Lake Christopher, MN 77765','734.546.8573','thomas64@gmail.com','7/11/2024','14/02/2029','Gibson, Nichols and Lang','Shawn Stewart','Anthony Brown','Ashley Perez','Carrie Harrison','PartialContribution',87307,928799);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'69-B-South','Mary Allen','0598 Natalie Hill, South Courtney, OR 42541','107-428-9568x44865','mendozadale@hotmail.com','4/9/2021','11/9/2029','Dickson, Tran and Stone','Joshua Cameron','Matthew Davis','Lacey Jones DVM','Angela Flores','FullContribution',84700,938754);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'52-C-South','Heather Deleon','845 Phillips Ridge Apt. 811, Clarkstad, CO 92956','(170)607-1930x13342','georgesuzanne@martinez.net','4/3/2021','25/08/2028','Casey, Simon and Jones','Mario Floyd','Elizabeth Walker','Bryan Cunningham','Melissa Calderon','PartialContribution',190903,930981);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'96-C-North','Bradley Barnes','819 Mccarthy Square Suite 838, South Jenniferville, UT 43973','3065938627','charles85@gmail.com','29/07/2021','19/04/2027','Holmes-Bush','Danny Boyd','Robert Cantu','Amy Johnson MD','Megan Robinson','PartialContribution',50411,924973);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'82-C-South','James Webb','09139 Diana Islands Apt. 783, Katherineside, GA 94260','659-273-0327x207','kleinkathy@gmail.com','18/04/2023','2/2/2028','Anderson, Santos and Mendoza','Stephanie Hart','Luis Henderson PhD','Michael Nunez','Timothy Brown','FullContribution',219745,935918);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'76-B-North','Donald Sullivan','5344 Eileen Passage, Lake Lori, TN 90849','+1-336-156-0002x59850','ofischer@evans-levine.com','22/12/2023','26/12/2026','Harper LLC','Nathaniel Sullivan','Nicholas Wood','Melissa Sweeney','Tanya Kelly','FullContribution',77136,997324);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'16-B-South','Samantha Morris','57899 Kaitlyn Circles Suite 921, Harringtonton, AZ 53287','037.293.8280x42717','yhenson@gutierrez.com','1/9/2024','20/08/2028','King, Baker and Bradford','Daniel Huynh','Ronald Moody','Stephanie Robinson','Adam Harris','PartialContribution',167056,938734);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'95-A-North','Matthew Walker','28880 Ashley Causeway Apt. 914, Drakeborough, CA 33833','+1-800-296-9073x77456','jenniferbowen@lowe.org','18/05/2024','2/9/2027','Graham, Turner and Harvey','Frederick Mclaughlin','Mark Moody','Paul Smith','Autumn Oliver','FullContribution',141324,960423);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'34-D-North','Sara Schmidt','9947 Devin Mission Suite 223, Port Travis, AR 18757','001-304-807-2967','mark36@yahoo.com','4/9/2022','15/06/2027','Johnson, Snyder and Sanders','Eric Gentry','Daniel Dalton','Kelly Smith','Andrew Sutton','PartialContribution',257638,952108);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'53-A-South','Amanda Rodriguez','Unit 9796 Box 1409, DPO AA 06717','001-066-775-4429x0179','gabriellesmith@taylor.com','10/2/2021','21/01/2028','Chaney-Alvarado','Angela Torres','Monique Thompson','Teresa Stewart','Kevin Butler','FullContribution',216029,985590);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'25-D-South','Eric Flores','765 Jesus Plain Apt. 450, Conleyborough, ID 05826','+1-929-455-3225x416','jeanettemunoz@campbell-crawford.com','25/06/2023','6/8/2029','Harvey-Martinez','Charles Meyer','Martin Taylor','Thomas Flowers','Stacy Lopez','FullContribution',102176,979266);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'60-B-North','Isabella Taylor','066 Golden Ports, Tylerburgh, CT 68365','396.531.4664x505','kathrynbrown@hotmail.com','27/02/2021','1/11/2027','Anderson-Nichols','Brandon Branch','Michael Sheppard','Vanessa Preston','Michael Johnson','FullContribution',260664,966381);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'96-D-South','Jillian Welch','997 Brad Corners, West Alanport, WA 12558','+1-181-200-3332x11562','jacob11@potter-martinez.info','25/08/2020','26/08/2026','Alvarez-Benton','Melinda Aguilar','Brian Fox','Michael Collins','Taylor Haas','FullContribution',238968,979137);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'83-B-North','Brandon Herrera','27449 Ortiz Mountain, Richview, NY 11526','369.506.8205','halldanielle@gmail.com','25/07/2024','11/9/2029','Noble-Higgins','Destiny Flores','Elijah Arnold','Ryan Pugh','Jennifer Mccullough','PartialContribution',291499,990745);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'47-A-North','Amanda Anderson','721 Alyssa Station, Reyesfurt, IN 92671','-9757','ilyons@mcdonald-carroll.com','24/07/2020','21/12/2029','Baker-Jones','Jamie Joseph','Jessica Morris','Gregory Wells','Darren Barton','PartialContribution',215312,981163);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'70-D-South','Mr. Erik Jones','55853 Dean Dam, East Michelemouth, NV 61924','401.622.5027x3980','hwaters@haas.com','26/10/2023','6/12/2027','Lopez-Rivera','Kathryn Bernard','Shannon Hamilton','Mark Rowe','Tyler Ortega','FullContribution',237790,935341);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'64-B-South','Stephen Bernard','PSC 9888, Box 4561, APO AP 36965','(866)594-2313x70734','weberjoel@scott.com','5/10/2022','19/01/2029','Bowers-Miller','Jennifer Russell','Tyler Cox','Elizabeth Terry','Lance Martinez','FullContribution',74293,924706);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'63-A-North','Linda Foster','92361 Ann Curve Suite 161, Port Jamesville, OH 32522','-9148','jeffreyward@miller.com','24/04/2022','30/12/2029','Harrison, Everett and Davis','Mark Bryant','Virginia Joseph','Randy George','Amy Mcgrath','FullContribution',196251,964112);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'62-A-North','Carrie Schmitt','5093 Kathryn Islands, Andersonchester, OR 65325','+1-219-740-0012x2824','fletchergregory@yahoo.com','9/9/2020','24/12/2028','Porter PLC','Steven Becker','Kyle Chase','Louis Hurley','Cameron Johnson','FullContribution',281106,984239);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'58-B-North','Katherine Hill','Unit 4554 Box 1935, DPO AE 45617','+1-263-760-8481x49774','jason55@rodriguez.com','12/5/2023','1/3/2028','Murphy, Simpson and Oliver','Roger Williams','Shane Carter III','Christine Arias','Andrew Campbell','FullContribution',176342,970465);
INSERT INTO mytable(columbary_ID,cr_vault_number,cr_full_name,cr_permanent_residence,cr_mobile_number,cr_email_address,cr_date_of_issuance,cr_date_of_expiration,cr_issuing_party,first_beneficiary,second_beneficiary,third_beneficiary,fourth_beneficiary,pa_type_of_p,pa_amount,pa_ref_number) VALUES (NULL,'30-D-South','Brandon Wilson','Unit 8085 Box 1998, DPO AP 63367','999-896-2079x42437','ericstein@garcia.org','17/05/2023','28/10/2029','Caldwell-Barrera','Kenneth Lewis','Suzanne Lindsey','Carrie Johnson','Jonathan Copeland','PartialContribution',264984,968559);
