# Generated by Django 5.1.2 on 2025-01-13 21:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ColumbaryRecord",
            fields=[
                (
                    "VaultID",
                    models.CharField(max_length=16, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                ("CustomerID", models.AutoField(primary_key=True, serialize=False)),
                ("Full_Name", models.CharField(max_length=45)),
                ("Permanent_Address", models.CharField(max_length=255)),
                (
                    "Landline_Number",
                    models.CharField(blank=True, max_length=7, null=True),
                ),
                (
                    "Mobile_Number",
                    models.CharField(blank=True, max_length=11, null=True),
                ),
                (
                    "Email_Address",
                    models.EmailField(blank=True, max_length=45, null=True),
                ),
                (
                    "COLUMBARY_RECORDS_VaultID",
                    models.ForeignKey(
                        blank=True,
                        db_column="COLUMBARY_RECORDS_VaultID",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="pages.columbaryrecord",
                    ),
                ),
            ],
        ),
    ]
