# Generated by Django 5.1.6 on 2025-02-21 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='columbaryrecord',
            table='columbaryrecord',
        ),
        migrations.AlterModelTable(
            name='payment',
            table='payment',
        ),
    ]
