# Generated by Django 5.1.2 on 2025-01-14 12:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="columbaryrecord",
            name="vault_id",
            field=models.CharField(max_length=7, primary_key=True, serialize=False),
        ),
    ]
