# Generated by Django 5.1.2 on 2025-02-24 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='columbaryrecord',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='columbaryrecord',
            name='issuance_date',
        ),
        migrations.RemoveField(
            model_name='columbaryrecord',
            name='issuing_parish_priest',
        ),
    ]
