# Generated by Django 5.1.2 on 2025-02-19 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="columbaryrecord",
            name="status",
            field=models.CharField(
                choices=[("Vacant", "Vacant"), ("Occupied", "Occupied")],
                default="Vacant",
                max_length=10,
            ),
        ),
    ]
