# Generated by Django 5.1.2 on 2025-02-19 07:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='holderofprivilege',
            old_name='address',
            new_name='issuing_parish_priest',
        ),
        migrations.RemoveField(
            model_name='columbaryrecord',
            name='expiration_date',
        ),
        migrations.RemoveField(
            model_name='columbaryrecord',
            name='issuance_date',
        ),
        migrations.RemoveField(
            model_name='columbaryrecord',
            name='issuing_parish_priest',
        ),
        migrations.RemoveField(
            model_name='holderofprivilege',
            name='email_address',
        ),
        migrations.RemoveField(
            model_name='holderofprivilege',
            name='full_name',
        ),
        migrations.RemoveField(
            model_name='holderofprivilege',
            name='landline_number',
        ),
        migrations.RemoveField(
            model_name='holderofprivilege',
            name='mobile_number',
        ),
        migrations.AddField(
            model_name='holderofprivilege',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privileges', to='pages.customer'),
        ),
        migrations.AddField(
            model_name='holderofprivilege',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='holderofprivilege',
            name='issuance_date',
            field=models.DateField(null=True),
        ),
    ]
