# Generated by Django 5.1.2 on 2025-02-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_remove_columbaryrecord_expiration_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columbaryrecord',
            name='urns_per_columbary',
            field=models.CharField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=1, null=True),
        ),
    ]
