# Generated by Django 5.1.2 on 2025-02-19 07:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_rename_address_holderofprivilege_issuing_parish_priest_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='holderofprivilege',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='privileges', to='pages.customer'),
        ),
    ]
