# Generated by Django 5.1.6 on 2025-02-23 22:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
    ('pages', '0001_initial'),
]

    operations = [
    ]
