# Generated by Django 5.1.2 on 2025-02-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_columbaryrecord_urns_per_columbary'),
    ]

    operations = [
        migrations.CreateModel(
            name='ParishKnowledge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('answer', models.TextField()),
            ],
        ),
    ]
