# Generated by Django 5.1.6 on 2025-02-24 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20250224_0629'),
    ]

    operations = [
    ]
