# Generated by Django 5.1.2 on 2025-02-17 12:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_remove_customer_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beneficiary',
            name='customer',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiaries', to='pages.customer'),
        ),
    ]
