# Generated by Django 5.1.6 on 2025-02-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_payment_created_at_alter_columbaryrecord_table_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='payment',
            table=None,
        ),
    ]
