# Generated by Django 5.1.2 on 2025-02-19 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_alter_holderofprivilege_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columbaryrecord',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='columbary_records', to='pages.customer'),
        ),
    ]
