# Generated by Django 5.1.2 on 2025-02-19 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_alter_columbaryrecord_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='columbaryrecord',
            name='customer',
            field=models.ForeignKey(db_column='customer_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='columbary_records', to='pages.customer'),
        ),
    ]
