# Generated by Django 5.1.2 on 2025-02-24 13:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_parishknowledge'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='parishknowledge',
            table='parish_knowledge',
        ),
    ]
