# Generated by Django 5.1.2 on 2025-02-19 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0006_alter_beneficiary_first_beneficiary_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiary',
            name='first_beneficiary_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='address_line_1',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='mode_of_payment',
            field=models.CharField(blank=True, choices=[('Full Payment', 'Full Payment'), ('6-Month Installment', '6-Month Installment')], max_length=20, null=True),
        ),
    ]
